version: 2

models:
  - name: customer_order_summary
    description: "Summary of total orders per customer for client A"
    columns:
      - name: customer_id
        tests:
          - not_null
      - name: total_orders
        tests:
          - not_null

  - name: average_stores_sales
    description: "Summary of total quantity of items by store for client A"
    columns:
      - name: stores_name
        tests:
          - not_null
          - unique
      - name: total_quantity
        tests:
          - not_null